### ISSUE TITLE
Tether will not compile in linux - Ubuntu Mate 18.04

### ISSUE THREAD

**Issue by kfox98** [koush/support-wiki#185]
~/Tether/node$ ./configure

Traceback (most recent call last):
  File "./configure", line 463, in <module>
    configure_node(output)
  File "./configure", line 370, in configure_node
    o['variables']['gcc_version'] = cc_version[0] + cc_version[1]
IndexError: tuple index out of range

**Comment by maledon** [comment]
this will get you past ./configure
go to line 325 in configure and change "+ ['-dumpversion']" to "+ ['-dumpfullversion']"
HOWEVER you will then get an error (or I do) when you make it
